version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  notificationservice-app:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mynetwork
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

networks:
  mynetwork:
